version: "3.8"
services:
  backend:
    build: .
    container_name: commonAssessmentTool-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  init-db:
    build: .
    depends_on:
      - backend
    volumes:
      - .:/app
    command: python initialize_data.py
