name: CI/CD Pipeline

on:
  push:
    branches: [master, main, xy-shen-sp3]
  pull_request:
    branches: [master, main, xy-shen-sp3]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  docker-test:
    needs: test # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t common-assessment-tool .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 common-assessment-tool
          sleep 10  # Wait for container to start

      - name: Test Docker container
        run: |
          curl http://localhost:8000/docs

  deploy:
    needs: docker-test
    if: github.ref == 'refs/heads/xy-shen-sp3'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/CommonAssessmentTool
            git pull origin main
            git checkout main
            docker-compose down
            docker-compose up -d --build
