name: Deploy Backend to EC2

on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/CommonAssessmentTool
            git pull origin main
            git checkout main
            docker-compose down
            docker-compose up -d --build
