name: Python Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true # Allow this job to fail

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flake8 autopep8

      - name: Run Pylint
        run: pylint $(git ls-files '*.py')
        continue-on-error: true # Allow this step to fail

      - name: Run Flake8
        run: flake8 --max-line-length=100 .
        continue-on-error: true # Allow this step to fail

